CREATE DATABASE Cinama
USE  Cinama

CREATE TABLE Films
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
ReleaseDate DATE NOT NULL,
)
 
CREATE TABLE Actors
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
Surname NVARCHAR(50) NOT NULL,
Age INT CHECK(Age>0 AND Age<166) NOT NULL
)

CREATE TABLE Genres
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE ActorsOfFilm
(
Id INT IDENTITY PRIMARY KEY,
FilmId INT REFERENCES Films(Id) NOT NULL,
ActorId INT REFERENCES Actors(Id) NOT NULL
)

CREATE TABLE GenresOfFilm
(
Id INT IDENTITY PRIMARY KEY,
FilmId INT REFERENCES Films(Id)NOT NULL,
GenreId INT REFERENCES Genres(Id)NOT NULL
)

CREATE TABLE Customers
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50)NOT NULL,
Surname NVARCHAR(50)NOT NULL,
Age INT CHECK(Age>0)NOT NULL
)

CREATE TABLE Halls
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
SeatCount INT CHECK(SeatCount>0) NOT NULL
)

CREATE TABLE Seances
(
	Id INT IDENTITY PRIMARY KEY,
	StartTime TIME NOT NULL
)

CREATE TABLE Tickets
(
Id INT IDENTITY PRIMARY KEY,
SoldDate DATETIME DEFAULT GETDATE(),
Price FLOAT CHECK(Price>0) NOT NULL,
Seat INT CHECK(Seat>0) NOT NULL,
SeanceId INT REFERENCES Seances(Id) NOT NULL,
HallId INT REFERENCES Halls(Id) NOT NULL,
CustomerId INT REFERENCES Customers(Id) NOT NULL,
FilmId INT REFERENCES Films(Id) NOT NULL
)


DROP TABLE Tickets
DROP TABLE Seances
DROP TABLE Halls
DROP TABLE Customers
DROP TABLE GenresOfFilm
DROP TABLE ActorsOfFilm
DROP TABLE Genres
DROP TABLE Actors
DROP TABLE Films

INSERT INTO Films VALUES('Shoushenkden Qacish','01-01-2021'),('The Godfather','02-01-2021'),('The Dark Knight','03-01-2021'),(' The Godfather: Part II','04-01-2021'),('12 Angry Men','05-01-2021'),('Shindlerin Siyahisi ','06-01-2021'),('Kriminal Qirayet','07-01-2021'),('Forrest Qamp','08-01-2021'),('Döyüshçü Klubu','09-01-2021'),('Inception','01-02-2021'),('The Matrix','01-03-2021'),('Goodfellas','01-04-2021')

INSERT INTO Actors VALUES
('ACTOR_NAME1','ACTOR_SURNAME1',20),('ACTOR_NAME2','ACTOR_SURNAME2',21),('ACTOR_NAME3','ACTOR_SURNAME3',23),
('ACTOR_NAME5','ACTOR_SURNAME4',24),('ACTOR_NAME6','ACTOR_SURNAME6',25),('ACTOR_NAME6','ACTOR_SURNAME6',26),
('ACTOR_NAME7','ACTOR_SURNAME7',27),('ACTOR_NAME8','ACTOR_SURNAME8',28),('ACTOR_NAME9','ACTOR_SURNAME9',29),
('ACTOR_NAME10','ACTOR_SURNAME10',30),('ACTOR_NAME11','ACTOR_SURNAME11',31),('ACTOR_NAME12','ACTORS_URNAME12',32)

INSERT INTO Genres VALUES
('Horror'),('Action'),('Adventure'),('Animated'),('Comedy'),('Drama'),
('Fantasy'),('Historical'),('Science'),('Thriller'),('Western'),('Zombie')

INSERT INTO ActorsOfFilm VALUES
(1,1),(2,2),(3,3),(4,4),(5,5),(6,6),
(1,2),(2,3),(3,4),(4,5),(5,6),(6,7)

INSERT INTO GenresOfFilm VALUES
(1,1),(2,2),(3,3),(4,4),(5,5),(6,6),
(1,2),(2,3),(3,4),(4,5),(5,6),(6,7)

INSERT INTO Halls VALUES
('HALL1',20),('HALL2',21),('HALL3',22),('HALL4',23),('HALL5',24),('HALL6',25),
('HALL7',26),('HALL8',27),('HALL9',28),('HALL10',29),('HALL11',30),('HALL12',31)

INSERT INTO Customers VALUES
('CUSTOMER_NAME1','CUSTOMER_SURNAME1',20),('CUSTOMER_NAME2','CUSTOMER_SURNAME2',21),('CUSTOMER_NAME3','CUSTOMER_SURNAME3',23),     
('CUSTOMER_NAME5','CUSTOMER_SURNAME4',24),('CUSTOMER_NAME6','CUSTOMER_SURNAME6',25),('CUSTOMER_NAME6','CUSTOMER_SURNAME6',26),     
('CUSTOMER_NAME7','CUSTOMER_SURNAME7',27),('CUSTOMER_NAME8','CUSTOMER_SURNAME8',28),('CUSTOMER_NAME9','CUSTOMER_SURNAME9',29),     
('CUSTOMER_NAME10','CUSTOMER_SURNAME10',30),('CUSTOMER_NAME11','CUSTOMER_SURNAME11',31),('CUSTOMER_NAME12','CUSTOMER_SURNAME12',32)

INSERT INTO Seances VALUES
('21:20'),('21:21'),('21:22'),('21:23'),('21:24'),('21:25'),
('21:26'),('21:27'),('21:28'),('21:29'),('21:30'),('21:31')

INSERT INTO Tickets VALUES
(DEFAULT,1,1,1,1,1,1),(DEFAULT,2,2,2,2,2,2),(DEFAULT,3,3,3,3,3,3),(DEFAULT,4,4,4,4,4,4),(DEFAULT,5,5,5,5,5,5),(DEFAULT,6,6,6,6,6,6),
(DEFAULT,1,2,3,4,5,6),(DEFAULT,2,3,4,5,6,1),(DEFAULT,3,4,5,6,1,2),(DEFAULT,4,5,6,1,2,3),(DEFAULT,5,6,1,2,3,4),(DEFAULT,6,5,4,3,2,1)


ALTER FUNCTION GetEmptySeat (@HallId INT, @SeanceId INT)
RETURNS INT AS
BEGIN
DECLARE @Count INT
SELECT @Count = Halls.SeatCount - COUNT(Seances.Id) FROM Tickets
Join Halls ON
Halls.Id = Tickets.HallId
Join Seances ON
Seances.Id = Tickets.SeanceId
WHERE @HallId = Halls.Id and @SeanceId = Tickets.SeanceId
GROUP BY Halls.SeatCount, Seances.Id

IF @COUNT IS NULL
BEGIN
	SELECT @Count =Halls.SeatCount FROM Tickets
	JOIN Halls
	ON Halls.Id=@HallId
	JOIN Seances
	ON Seances.Id =@SeanceId
END
	Return @Count
End

SELECT dbo.GetEmptySeat(4,7)